[pytest]
# Configuración de ejecución predeterminada
addopts = --clean-alluredir --alluredir=allure-results -vs

# Ubicación del directorio de pruebas
testpaths = tests

# Patrones para descubrimiento automático de archivos y funciones de prueba
python_files = test_*.py
python_classes = Test*
python_functions = test_*